package Specs;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package optometrists;

/**
 *
 * @author Omen
 */
public class Specialist extends javax.swing.JFrame {

    /**
     * Creates new form Opto
     */
    public Specialist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OtpoBtn = new javax.swing.JButton();
        SpecialistBackground = new javax.swing.JPanel();
        SpecalistTxt = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        GynoBtn = new javax.swing.JButton();
        NeuroBtn = new javax.swing.JButton();
        PedaBtn = new javax.swing.JButton();
        DermaBtn = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();

