package Admin;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Omen
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jpanelbackground = new javax.swing.JPanel();
        jlabelAdminPanel = new javax.swing.JLabel();
        DoctorBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        PatientBtn = new javax.swing.JButton();
        jLbackground = new javax.swing.JLabel();
        jbanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Panel");
        setBackground(new java.awt.Color(255, 255, 255));

        jpanelbackground.setBackground(new java.awt.Color(255, 255, 255));
        jpanelbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelAdminPanel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jlabelAdminPanel.setText("Admin Panel");
        jpanelbackground.add(jlabelAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 220, 40));

        DoctorBtn.setBackground(new java.awt.Color(0, 146, 255));
        DoctorBtn.setText("Doctor");
        DoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorBtnActionPerformed(evt);
            }
        });
        jpanelbackground.add(DoctorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, 120));

        AdminBtn.setBackground(new java.awt.Color(0, 146, 255));
        AdminBtn.setText("Admin");
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });
        jpanelbackground.add(AdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 180, 120));

        PatientBtn.setBackground(new java.awt.Color(0, 146, 255));
        PatientBtn.setText("Patient");
        PatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientBtnActionPerformed(evt);
            }
        });
        jpanelbackground.add(PatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 180, 120));

        jLbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optometrists/Background.jpg"))); // NOI18N
        jLbackground.setText("jLabel1");
        jpanelbackground.add(jLbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 630, 460));

        jbanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optometrists/banner.jpg"))); // NOI18N
        jbanner.setText("jLabel1");
        jpanelbackground.add(jbanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 630, 240));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpanelbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jpanelbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void DoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void PatientBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }



