package Admin;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Omen
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jpanelbackground = new javax.swing.JPanel();
        jlabelAdminPanel = new javax.swing.JLabel();
        DoctorBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        PatientBtn = new javax.swing.JButton();
        jLbackground = new javax.swing.JLabel();
        jbanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Panel");
        setBackground(new java.awt.Color(255, 255, 255));

        jpanelbackground.setBackground(new java.awt.Color(255, 255, 255));
        jpanelbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelAdminPanel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jlabelAdminPanel.setText("Admin Panel");
        jpanelbackground.add(jlabelAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 220, 40));

        DoctorBtn.setBackground(new java.awt.Color(0, 146, 255));
        DoctorBtn.setText("Doctor");
        DoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorBtnActionPerformed(evt);
            }
        });

